### ISSUE TITLE
Unable to start Debugger inside docker

### ISSUE THREAD

**Issue by anishkargaonkar** [ilourt/gocker#3]
- Delve github package path needs to be updated in the script ```/go/src/app/start.sh``` from
```github.com/derekparker/delve/cmd/dlv``` -> ```github.com/go-delve/delve/cmd/dlv```

- Give delve permission to debug in the ```docker-compose.yml``` by setting ```security_opt``` option.

#### /go/src/app/start.sh
```
#!/bin/sh

if [ "$GO_DEP" = true ]; then
  go get -u github.com/golang/dep/cmd/dep
  dep init
  dep ensure -update
else
  go install -v .
fi

if [ "$DEBUG" = true ] ; then
  go get github.com/go-delve/delve/cmd/dlv
  go get github.com/cortesi/modd/cmd/modd
  modd -f ./modd-debug.conf
fi

if [ "$WATCH" = true ] ; then
  go get github.com/cortesi/modd/cmd/modd
  modd
fi

if [ "$BUILD" = true ] ; then
  go build -o $BIN_NAME .
  if [ "$EXEC" = true ] ; then
    ./$BIN_NAME
  fi
fi
```

#### docker-compose.yml
```
version: '3'
services:
  golang:
    build:
      context: .
      args:
        USER: gocker
        UID: 1000
    image: gocker
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./go:/go
    command: sh ./start.sh
    env_file:
      - .env
    ports:
      - 2345:2345 # Ports using for debuging with dlv
```
